project:
  type: website
  output-dir: docs  

website:
  title: "Mercado Laboral Ecuador 2026"
  description: "Análisis de estabilidad laboral y factores determinantes mediante ENEMDU."
  
  # Configuración del Menú Superior
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Preparación de Datos"
        file: data_cleaning.qmd
      - text: "Visualizaciones"
        file: visualizations.qmd
    right:
      - icon: github
        href: https://github.com/fernandoDeveloping/analisis-empleo-ecuador-2026

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true
    toc-title: "En esta página"
    code-fold: true  
    code-summary: "Mostrar código"
    code-copy: true
    lang: es         

# Configuración de ejecución de celdas
execute:
  freeze: auto       