{
  "hash": "1d4763efe40581bd6c68bc60239998bd",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Limpieza y Preparación de Datos\"\nsubtitle: \"ENEMDU — Encuesta Nacional de Empleo, Desempleo y Subempleo | Enero 2026\"\nexecute:\n  warning: false\n  message: false\n---\n\n## Introducción\n\nEste documento registra el proceso de limpieza y preparación de los datos provenientes de la **ENEMDU (Encuesta Nacional de Empleo, Desempleo y Subempleo)** del período enero 2026, publicada por el INEC. El objetivo es transformar el archivo fuente en formato `.sav` (SPSS) en un dataset estructurado y limpio, listo para el análisis visual.\n\nEl flujo de ejecución sigue este orden estricto para evitar errores de columna no encontrada:\n\n1. Carga del archivo fuente\n2. Exploración inicial sobre los datos crudos\n3. Recodificación de `condact` (base de todas las variables derivadas)\n4. Construcción de horas trabajadas totales\n5. Manejo de valores faltantes (sobre columnas ya existentes)\n6. Mapeo de ciudades y etnia\n7. Selección final, renombrado y exportación\n\n---\n\n## Carga del Dataset\n\n### Librerías necesarias\n\n::: {#32dfd3db .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n```\n:::\n\n\n> **Justificación:** `pandas` maneja la lectura del `.sav` y todas las transformaciones tabulares. `numpy` permite operaciones vectorizadas eficientes equivalentes al `RECODE` y `COMPUTE` de SPSS.\n\n### Lectura del archivo SPSS\n\n::: {#609b7bae .cell execution_count=2}\n``` {.python .cell-code}\nfile_path = 'SPSS/enemdu_persona_2026_01.sav'\ndf = pd.read_spss(file_path)\n\nprint(f\"Filas cargadas:       {df.shape[0]:,}\")\nprint(f\"Columnas disponibles: {df.shape[1]}\")\n\n\nfor col in df.select_dtypes(['category', 'object']).columns:\n    try:\n        df[col] = df[col].astype(str).str.strip()\n        df[col] = df[col].replace('nan', float('nan'))\n    except Exception:\n        pass\n\n# ── Mapear columnas Categorical clave a numérico ─────────────────\n\n# area: Urbana/Rural -> 1/2\ndf['area'] = df['area'].map({'Urbana': 1, 'Rural': 2})\nprint(\"Area:\", df['area'].value_counts().to_dict())\n\n# p10a: nivel educativo -> escala numérica ordinal\nmapa_p10a = {\n    'Ninguno': 1,\n    'Centro de alfabetización': 2,\n    'Jardín de infantes': 3,\n    'Primaria': 4,\n    'Educación Básica': 5,\n    'Secundaria': 6,\n    'Educación  Media': 7,\n    'Educación Media': 7,\n    'Superior no universitario': 8,\n    'Superior Universitario': 9,\n    'Post-grado': 10\n}\ndf['p10a'] = df['p10a'].map(mapa_p10a)\nprint(\"Nivel educativo:\", df['p10a'].value_counts().to_dict())\n\n# p02: género -> 1=Hombre, 2=Mujer\ndf['p02'] = df['p02'].map({'Hombre': 1, 'Mujer': 2})\n\n# p05b: seguro -> numérico si viene como texto\nmapa_seguro = {\n    'IESS, seguro general': 1,\n    'IESS, seguro voluntario': 2,\n    'IESS, seguro campesino': 3,\n    'Es jubilado del IESS/ISSFA/ISSPOL': 4,\n    'Issfa o Isspol': 4,\n    'Seguro privado': 5,\n    'Ninguno': 6,\n    'No sabe': 7\n}\ndf['p05b'] = df['p05b'].map(mapa_seguro).fillna(\n    pd.to_numeric(df['p05b'], errors='coerce')\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFilas cargadas:       27,528\nColumnas disponibles: 142\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nArea: {1: 20200, 2: 7328}\nNivel educativo: {6.0: 5231, 5.0: 5175, 4.0: 5098, 9.0: 4541, 7.0: 3737, 8.0: 808, 10.0: 788, 1.0: 778, 2.0: 18}\n```\n:::\n:::\n\n\n> **Justificación:** `pd.read_spss()` preserva automáticamente las etiquetas de valor (*value labels*) del archivo, lo que permite verificar la codificación original antes de cualquier transformación. En esta versión de la ENEMDU, variables como `condact` vienen como texto etiquetado y deben recodificarse antes de usarse analíticamente.\n\n---\n\n## Exploración Inicial del Dataset\n\nEsta sección se ejecuta **sobre los datos crudos**, antes de cualquier modificación.\n\n### Vista previa de `condact`\n\n::: {#3e673538 .cell execution_count=3}\n``` {.python .cell-code}\n# condact llega como categoría de texto desde el .sav\ndf['condact'].head()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n0    Población Económicamente Inactiva\n1    Población Económicamente Inactiva\n2                Empleo Adecuado/Pleno\n3                 Otro empleo no pleno\n4                 Otro empleo no pleno\nName: condact, dtype: str\n```\n:::\n:::\n\n\n### Resumen de tipos y valores faltantes\n\n::: {#2659e2bd .cell execution_count=4}\n``` {.python .cell-code}\n# Resumen compacto: tipo de dato y proporción de NaN por columna\nresumen = pd.DataFrame({\n    'tipo': df.dtypes,\n    'nulos': df.isna().sum(),\n    'pct_nulo': (df.isna().mean() * 100).round(1),\n    'valores_unicos': df.nunique()\n})\nresumen[resumen['nulos'] > 0].sort_values('pct_nulo', ascending=False).head(20)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>tipo</th>\n      <th>nulos</th>\n      <th>pct_nulo</th>\n      <th>valores_unicos</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>p35</th>\n      <td>str</td>\n      <td>27463</td>\n      <td>99.8</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>p78</th>\n      <td>str</td>\n      <td>27449</td>\n      <td>99.7</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>p74b</th>\n      <td>float64</td>\n      <td>27347</td>\n      <td>99.3</td>\n      <td>27</td>\n    </tr>\n    <tr>\n      <th>p70b</th>\n      <td>float64</td>\n      <td>27305</td>\n      <td>99.2</td>\n      <td>53</td>\n    </tr>\n    <tr>\n      <th>p233</th>\n      <td>str</td>\n      <td>27150</td>\n      <td>98.6</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>p232</th>\n      <td>str</td>\n      <td>27150</td>\n      <td>98.6</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>p23</th>\n      <td>str</td>\n      <td>27150</td>\n      <td>98.6</td>\n      <td>5</td>\n    </tr>\n    <tr>\n      <th>p39</th>\n      <td>str</td>\n      <td>27114</td>\n      <td>98.5</td>\n      <td>31</td>\n    </tr>\n    <tr>\n      <th>p38</th>\n      <td>str</td>\n      <td>27114</td>\n      <td>98.5</td>\n      <td>7</td>\n    </tr>\n    <tr>\n      <th>p54a</th>\n      <td>str</td>\n      <td>27079</td>\n      <td>98.4</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>p71b</th>\n      <td>float64</td>\n      <td>27085</td>\n      <td>98.4</td>\n      <td>62</td>\n    </tr>\n    <tr>\n      <th>p69</th>\n      <td>float64</td>\n      <td>26973</td>\n      <td>98.0</td>\n      <td>71</td>\n    </tr>\n    <tr>\n      <th>p70a</th>\n      <td>str</td>\n      <td>26973</td>\n      <td>98.0</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>p33</th>\n      <td>str</td>\n      <td>26980</td>\n      <td>98.0</td>\n      <td>27</td>\n    </tr>\n    <tr>\n      <th>sd03</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>8</td>\n    </tr>\n    <tr>\n      <th>sd01</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>sd023</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>2</td>\n    </tr>\n    <tr>\n      <th>sd029</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>sd0211</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>sd0210</th>\n      <td>str</td>\n      <td>26929</td>\n      <td>97.8</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Justificación:** En lugar de imprimir la distribución completa de cada columna, se muestra un resumen compacto que permite identificar rápidamente qué variables tienen mayor proporción de valores faltantes — suficiente para diagnosticar el diseño condicional del cuestionario y decidir la estrategia de limpieza.\n\n---\n\n## Recodificación de `condact`\n\nLa variable `condact` llega como texto etiquetado desde el `.sav`. Se mapea a la escala numérica oficial del INEC antes de cualquier otra transformación, ya que varias variables dependen de ella.\n\n::: {#625316de .cell execution_count=5}\n``` {.python .cell-code}\n# Mapeo de etiquetas de texto a códigos numéricos oficiales INEC\n# Fuente: https://anda.inec.gob.ec/anda/index.php/catalog/1048/datafile/F17/V1815\nmapa_condact = {\n    \"Empleo Adecuado/Pleno\": 1,\n    \"Subempleo por insuficiencia de tiempo de trabajo\": 2,\n    \"Subempleo por insuficiencia de ingresos\": 3,\n    \"Otro empleo no pleno\": 4,\n    \"Empleo no remunerado\": 5,\n    \"Empleo no clasificado\": 6,\n    \"Desempleo abierto\": 7,\n    \"Desempleo oculto\": 8,\n    \"Población Económicamente Inactiva\": 9\n}\n\ndf[\"condact\"] = df[\"condact\"].map(mapa_condact)\n\n# Menores de 15 años reciben código 0: quedan fuera de la PET\n# p03 viene como string tras el strip global -> convertir a numérico primero\ndf[\"p03\"] = pd.to_numeric(df[\"p03\"], errors='coerce')\ndf.loc[df['p03'] < 15, 'condact'] = 0\n\nprint(\"Distribución de condact tras recodificación:\")\nprint(df[\"condact\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistribución de condact tras recodificación:\ncondact\n9.0    8351\n1.0    5814\n0.0    5404\n4.0    3949\n2.0    2262\n5.0    1010\n7.0     548\n3.0      97\n8.0      50\n6.0      43\nName: count, dtype: int64\n```\n:::\n:::\n\n\n> **Justificación:** La escala numérica 1–9 permite usar `.between()` para definir subpoblaciones de forma compacta. El código 0 para menores de 15 años los excluye explícitamente de la Población en Edad de Trabajar (PET), en línea con la metodología INEC. Este paso debe ocurrir antes del manejo de NaN porque los filtros de edad usan `p03`.\n\n---\n\n## Construcción de Horas Trabajadas Totales\n\nEl archivo fuente no incluye una variable de horas totales precalculada. Se construye sumando las horas del empleo principal (`p51a`) y del empleo secundario (`p51b`), que son las únicas columnas con valores numéricos de horas en el cuestionario.\n\n::: {#87458de9 .cell execution_count=6}\n``` {.python .cell-code}\n# Convertir a numérico (vienen como Categorical desde el .sav)\ndf['p51a'] = pd.to_numeric(df['p51a'], errors='coerce')  # horas empleo principal\ndf['p51b'] = pd.to_numeric(df['p51b'], errors='coerce')  # horas empleo secundario\n\n# Horas totales = suma de ambos empleos (NaN si no trabaja en ninguno)\ndf['horas_trabajo_totales'] = df['p51a'].add(df['p51b'], fill_value=0)\ndf.loc[df['p51a'].isna() & df['p51b'].isna(), 'horas_trabajo_totales'] = np.nan\n\n# Versión para visualización: 0 en lugar de NaN (inactivos y desempleados)\ndf['horas_visual'] = df['horas_trabajo_totales'].fillna(0)\n\nprint(\"Distribución de horas totales trabajadas:\")\nprint(df['horas_trabajo_totales'].describe())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistribución de horas totales trabajadas:\ncount    13297.000000\nmean        35.888772\nstd         13.288100\nmin          1.000000\n25%         28.000000\n50%         40.000000\n75%         40.000000\nmax        120.000000\nName: horas_trabajo_totales, dtype: float64\n```\n:::\n:::\n\n\n> **Justificación:** `p51a` registra horas en el trabajo principal y `p51b` en el secundario. Se usa `fill_value=0` en la suma para que quien solo tiene un empleo no pierda sus horas por el NaN del otro. Sin embargo, si ambas columnas son NaN (persona sin empleo), el resultado se fuerza a NaN para no introducir ceros artificiales en los promedios de ocupados.\n\n---\n\n## Manejo de Valores Faltantes\n\nEsta sección opera **sobre columnas que ya existen** en el dataframe. Ejecutarla antes de la recodificación y construcción de variables causaría `KeyError`.\n\nLa ENEMDU tiene diseño de cuestionario condicional: preguntas sobre búsqueda de empleo solo se hacen a desempleados, preguntas laborales solo a ocupados, etc. Los NaN en esas variables son **ausencias estructurales por diseño**, no errores de medición.\n\n### Variables categóricas: NaN → `\"No hay dato\"`\n\n::: {#97cd57d1 .cell execution_count=7}\n``` {.python .cell-code}\n# p06 = estado_civil | p07 = asiste_a_clases\n# Estas columnas son Categorical, por lo que se convierte a str antes de rellenar.\ncols_cat = ['p06', 'p07']\nfor col in cols_cat:\n    df[col] = df[col].astype(str).replace('nan', 'No hay dato')\n```\n:::\n\n\n> **Justificación:** Las columnas Categorical de SPSS no admiten valores nuevos sin registrarlos primero como categoría válida. Convertir a `str` resuelve esto y produce una columna de texto directamente usable en gráficos. El valor `'nan'` que genera `.astype(str)` se reemplaza por la etiqueta `'No hay dato'` para claridad visual.\n\n---\n\n## Mapeo de Variables Geográficas y Sociodemográficas\n\n### Mapeo de ciudades\n\n::: {#373a7a3d .cell execution_count=8}\n``` {.python .cell-code}\n# El catálogo traduce los códigos numéricos del .sav a nombres legibles\nciudades = pd.read_excel('SPSS/Ciudades.xlsx')\nciudades.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Value</th>\n      <th>Category</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>90150</td>\n      <td>Guayaquil</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>170150</td>\n      <td>Quito</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>130850</td>\n      <td>Manta</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>80150</td>\n      <td>Esmeraldas</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>110150</td>\n      <td>Loja</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#3f5ff73b .cell execution_count=9}\n``` {.python .cell-code}\n# ciudad viene como float64 (ej. 10150.0) y el catálogo tiene int64 (10150).\n# Se convierte a Int64 nullable para alinear tipos sin perder los NaN.\ndf['ciudad'] = df['ciudad'].astype('Int64').map(ciudades.set_index('Value')['Category'])\ndf['ciudad'] = df['ciudad'].fillna('No hay dato')\n\nprint(f\"Ciudades distintas en la muestra: {df['ciudad'].nunique()}\")\ndf['ciudad'].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCiudades distintas en la muestra: 331\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nciudad\nGuayaquil                         3026\nQuito                             2633\nMachala                           2205\nCuenca                            1908\nAmbato                            1609\nEsmeraldas                         582\nSanto domingo de los colorados     434\nIbarra                             423\nLoja                               388\nNueva loja                         314\nName: count, dtype: int64\n```\n:::\n:::\n\n\n> **Justificación:** El archivo `.sav` almacena ciudades como `float64` (ej. `10150.0`) mientras que el catálogo `Ciudades.xlsx` usa `int64` (`10150`). La discrepancia de tipo impide el mapeo directo. Convertir a `Int64` nullable de pandas alinea los tipos sin perder los NaN, permitiendo que `.map()` encuentre todas las correspondencias correctamente.\n\n### Construcción de `adec` (empleo adecuado)\n\n::: {#c299410b .cell execution_count=10}\n``` {.python .cell-code}\n# adec no viene precalculada en el archivo; se deriva de condact\n# condact == 1 corresponde a Empleo Adecuado/Pleno\ndf['adec'] = np.where(df['condact'] == 1, 1.0, np.nan)\n```\n:::\n\n\n> **Justificación:** A diferencia de `empleo` y `desempleo`, la variable `adec` no viene en el archivo fuente. Se construye desde `condact` ya recodificado: código 1 = Empleo Adecuado/Pleno. Se usa `np.nan` en lugar de `0` para ser consistente con la convención de indicadores del INEC.\n\n### Mapeo de etnia\n\n::: {#eff2da6a .cell execution_count=11}\n``` {.python .cell-code}\n# La etnia está en p15 (autoidentificación étnica)\nmapping_etnia = {\n    1: 'Mestizo',\n    2: 'Indígena',\n    3: 'Afro/Negro',\n    4: 'Mulato',\n    5: 'Blanco',\n    6: 'Otros'\n}\ndf['etnia_nombre'] = pd.to_numeric(df['p15'], errors='coerce') \\\n                       .map(mapping_etnia).fillna('No hay dato')\n```\n:::\n\n\n> **Justificación:** La variable de autoidentificación étnica se encuentra en `p15`, no en una columna llamada `etnia`. Se convierte a numérico primero porque viene como Categorical desde el `.sav`, y se rellena con `'No hay dato'` para no excluir registros.\n\n---\n\n## Selección Final de Variables\n\nSe selecciona el subconjunto relevante para el análisis visual y se renombran con etiquetas descriptivas en español. **Este paso ocurre al final**, después de que todas las columnas necesarias han sido creadas.\n\n::: {#a105309d .cell execution_count=12}\n``` {.python .cell-code}\ndf_final = df[[\n    'horas_trabajo_totales', 'horas_visual',\n    'area', 'ciudad', 'etnia_nombre',\n    'condact', 'empleo', 'desempleo', 'adec',\n    'p01', 'p02', 'p03', 'p05b', 'p06', 'p07',\n    'p10a', 'p32', 'p38', 'p42', 'p45',\n    'ingrl', 'ingpc'\n]].rename(columns={\n    'p01':          'personas_hogar',\n    'p02':          'genero',\n    'p03':          'edad',\n    'p05b':         'seguro',\n    'p06':          'estado_civil',\n    'p07':          'asiste_a_clases',\n    'condact':      'condicion_actividad',\n    'adec':         'empleo_adecuado',\n    'p10a':         'nivel_educativo',\n    'p45':          'tiempo_experiencia',\n    'p32':          'como_busca_empleo',\n    'p38':          'razon_dejo_trabajo',\n    'p42':          'ocupacion_actual',\n    'etnia_nombre': 'etnia',\n    'ingrl':        'ingreso_laboral',\n    'ingpc':        'ingreso_per_capita'\n})\n```\n:::\n\n\n> **Justificación:** Se incluyen `ingrl` e `ingpc` porque el archivo sí las trae precalculadas y son relevantes para el análisis laboral. Se excluyen variables operativas del cuestionario (identificadores de vivienda, hogar, conglomerado) que no aportan al análisis sustantivo.\n\n### Verificación del dataset final\n\n::: {#db80f5c8 .cell execution_count=13}\n``` {.python .cell-code}\ndf_final.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 27528 entries, 0 to 27527\nData columns (total 22 columns):\n #   Column                 Non-Null Count  Dtype  \n---  ------                 --------------  -----  \n 0   horas_trabajo_totales  13297 non-null  float64\n 1   horas_visual           27528 non-null  float64\n 2   area                   27528 non-null  int64  \n 3   ciudad                 27528 non-null  str    \n 4   etnia                  27528 non-null  str    \n 5   condicion_actividad    27528 non-null  float64\n 6   empleo                 13175 non-null  str    \n 7   desempleo              598 non-null    str    \n 8   empleo_adecuado        5814 non-null   float64\n 9   personas_hogar         27528 non-null  str    \n 10  genero                 27528 non-null  int64  \n 11  edad                   27507 non-null  float64\n 12  seguro                 27278 non-null  float64\n 13  estado_civil           23507 non-null  str    \n 14  asiste_a_clases        26174 non-null  str    \n 15  nivel_educativo        26174 non-null  float64\n 16  como_busca_empleo      12877 non-null  str    \n 17  razon_dejo_trabajo     414 non-null    str    \n 18  ocupacion_actual       13711 non-null  str    \n 19  tiempo_experiencia     13297 non-null  str    \n 20  ingreso_laboral        11989 non-null  str    \n 21  ingreso_per_capita     27300 non-null  float64\ndtypes: float64(8), int64(2), str(12)\nmemory usage: 4.6 MB\n```\n:::\n:::\n\n\n::: {#bf5c49ec .cell execution_count=14}\n``` {.python .cell-code}\nprint(f\"Total filas:    {len(df_final):,}\")\nprint(f\"Total columnas: {len(df_final.columns)}\")\nprint(f\"Ciudades representadas: {df_final['ciudad'].nunique()}\")\ndf_final['ciudad'].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal filas:    27,528\nTotal columnas: 22\nCiudades representadas: 331\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nciudad\nGuayaquil                         3026\nQuito                             2633\nMachala                           2205\nCuenca                            1908\nAmbato                            1609\nEsmeraldas                         582\nSanto domingo de los colorados     434\nIbarra                             423\nLoja                               388\nNueva loja                         314\nName: count, dtype: int64\n```\n:::\n:::\n\n\n---\n\n## Exportación del Dataset Limpio\n\n::: {#cd316acb .cell execution_count=15}\n``` {.python .cell-code}\ncols_numericas = [\n    'edad', 'personas_hogar', 'nivel_educativo',\n    'condicion_actividad', 'empleo_adecuado', 'desempleado',\n    'horas_trabajo_totales', 'horas_visual',\n    'ingreso_laboral', 'ingreso_per_capita'\n]\nfor col in cols_numericas:\n    if col in df_final.columns:\n        df_final[col] = pd.to_numeric(df_final[col], errors='coerce')\n\n# area viene como Categorical texto ('Urbana'/'Rural') -> convertir a código numérico\nif 'area' in df_final.columns:\n    df_final['area'] = df_final['area'].astype(str).map(\n        {'Urbana': 1, 'Rural': 2, '1.0': 1, '2.0': 2, '1': 1, '2': 2}\n    )\n\n# genero y seguro pueden venir como Categorical -> numérico\nfor col in ['genero', 'seguro']:\n    if col in df_final.columns:\n        df_final[col] = pd.to_numeric(df_final[col], errors='coerce')\n\n# empleo y desempleado vienen como texto etiquetado desde el .sav\n# los convertimos a 1.0/NaN para que sean usables como indicadores\nif 'empleo' in df_final.columns:\n    df_final['empleo'] = df_final['empleo'].map(\n        lambda x: 1.0 if str(x).strip() in ['Población con empleo', '1.0', '1'] else float('nan')\n    )\nif 'desempleado' in df_final.columns:\n    df_final['desempleado'] = df_final['desempleado'].map(\n        lambda x: 1.0 if str(x).strip() in ['Población con desempleo', '1.0', '1'] else float('nan')\n    )\n\ndf_final.to_csv('SPSS/ENEMDU_clean.csv', index=False)\nprint('Dataset exportado exitosamente → SPSS/ENEMDU_clean.csv')\nprint(df_final[['area','genero','nivel_educativo','ingreso_laboral','empleo_adecuado']].dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset exportado exitosamente → SPSS/ENEMDU_clean.csv\narea                 int64\ngenero               int64\nnivel_educativo    float64\ningreso_laboral    float64\nempleo_adecuado    float64\ndtype: object\n```\n:::\n:::\n\n\n> **Justificación:** Se exporta en CSV para garantizar compatibilidad con las herramientas de visualización (Altair, Plotly, etc.) y facilitar el control de versiones. El archivo fuente `.sav` original no se modifica en ningún momento.\n\n---\n\n## Resumen de Decisiones de Limpieza\n\n| Decisión | Columnas afectadas | Razón |\n|---|---|---|\n| Explorar antes de transformar | Todas | Diagnosticar tipos, NaN y columnas precalculadas |\n| Recodificar `condact` primero | `condact` | Base de todas las variables derivadas; debe ser numérico |\n| Código 0 para menores de 15 | `condact`, `p03` | Metodología INEC: PET inicia a los 15 años |\n| No reconstruir variables precalculadas | `empleo`, `desempleo`, `adec` | El `.sav` ya las trae; recalcularlas introduciría inconsistencias |\n| Horas = `p51a + p51b` | `horas_trabajo_totales` | Única fuente numérica de horas en el cuestionario |\n| NaN bilateral → NaN en horas | `horas_trabajo_totales` | Evita introducir ceros para inactivos en promedios de ocupados |\n| `.astype(str)` antes de rellenar | `p06`, `p07`, `ciudad` | Columnas Categorical no admiten categorías nuevas directamente |\n| `'No hay dato'` en categóricas | `ciudad`, `estado_civil`, `asiste_a_clases`, `etnia` | Evita excluir registros en visualizaciones agregadas |\n| Renombrado al final en `df_final` | Todas las seleccionadas | Evita `KeyError` al usar nombres descriptivos antes de que existan |\n| Exportación CSV | — | Compatibilidad universal con herramientas de visualización |\n\n",
    "supporting": [
      "data_cleaning_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}