{
  "hash": "0f6895df89e4e7345d46b332a626311a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Limpieza y Preparación de Datos\"\nsubtitle: \"ENEMDU — Encuesta Nacional de Empleo, Desempleo y Subempleo | Enero 2026\"\nauthor: \"Análisis de Mercado Laboral\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    toc-title: \"Contenido\"\n    code-fold: false\n    code-tools: true\n    theme: flatly\n    highlight-style: github\n    number-sections: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Introducción\n\nEste documento registra el proceso de limpieza y preparación de los datos provenientes de la **ENEMDU (Encuesta Nacional de Empleo, Desempleo y Subempleo)** del período enero 2026, publicada por el INEC. El objetivo es transformar el archivo fuente en formato `.sav` (SPSS) en un dataset estructurado y limpio, listo para el análisis visual.\n\nEl flujo de ejecución sigue este orden estricto para evitar errores de columna no encontrada:\n\n1. Carga del archivo fuente\n2. Exploración inicial sobre los datos crudos\n3. Recodificación de `condact` (base de todas las variables derivadas)\n4. Construcción de horas trabajadas totales\n5. Manejo de valores faltantes (sobre columnas ya existentes)\n6. Mapeo de ciudades y etnia\n7. Selección final, renombrado y exportación\n\n---\n\n## Carga del Dataset\n\n### Librerías necesarias\n\n::: {#3110914e .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\n```\n:::\n\n\n> **Justificación:** `pandas` maneja la lectura del `.sav` y todas las transformaciones tabulares. `numpy` permite operaciones vectorizadas eficientes equivalentes al `RECODE` y `COMPUTE` de SPSS.\n\n### Lectura del archivo SPSS\n\n::: {#c5fe1a00 .cell execution_count=2}\n``` {.python .cell-code}\nfile_path = 'SPSS/enemdu_persona_2026_01.sav'\ndf = pd.read_spss(file_path)\n\nprint(f\"Filas cargadas:       {df.shape[0]:,}\")\nprint(f\"Columnas disponibles: {df.shape[1]}\")\n\n# Mapear area a numérico AQUÍ, antes de cualquier otra transformación.\n# Viene como Categorical 'Urbana'/'Rural' y pd.to_numeric la destruiría más adelante.\n# ── Limpiar espacios en TODAS las columnas Categorical ───────────\n# El .sav de la ENEMDU incluye espacios al inicio/fin en muchas etiquetas\n# de texto. Si no se limpian, los mapeos y filtros posteriores fallan\n# silenciosamente devolviendo NaN en lugar de un error claro.\nfor col in df.select_dtypes(['category', 'object']).columns:\n    try:\n        df[col] = df[col].astype(str).str.strip()\n        df[col] = df[col].replace('nan', float('nan'))\n    except Exception:\n        pass\n\n# ── Mapear columnas Categorical clave a numérico ─────────────────\n# Se hace ANTES de pd.to_numeric para evitar que las convierta a NaN\n\n# area: Urbana/Rural -> 1/2\ndf['area'] = df['area'].map({'Urbana': 1, 'Rural': 2})\nprint(\"Area:\", df['area'].value_counts().to_dict())\n\n# p10a: nivel educativo -> escala numérica ordinal\nmapa_p10a = {\n    'Ninguno': 1,\n    'Centro de alfabetización': 2,\n    'Jardín de infantes': 3,\n    'Primaria': 4,\n    'Educación Básica': 5,\n    'Secundaria': 6,\n    'Educación  Media': 7,\n    'Educación Media': 7,\n    'Superior no universitario': 8,\n    'Superior Universitario': 9,\n    'Post-grado': 10\n}\ndf['p10a'] = df['p10a'].map(mapa_p10a)\nprint(\"Nivel educativo:\", df['p10a'].value_counts().to_dict())\n\n# p02: género -> 1=Hombre, 2=Mujer\ndf['p02'] = df['p02'].map({'Hombre': 1, 'Mujer': 2})\n\n# p05b: seguro -> numérico si viene como texto\nmapa_seguro = {\n    'IESS, seguro general': 1,\n    'IESS, seguro voluntario': 2,\n    'IESS, seguro campesino': 3,\n    'Es jubilado del IESS/ISSFA/ISSPOL': 4,\n    'Issfa o Isspol': 4,\n    'Seguro privado': 5,\n    'Ninguno': 6,\n    'No sabe': 7\n}\ndf['p05b'] = df['p05b'].map(mapa_seguro).fillna(\n    pd.to_numeric(df['p05b'], errors='coerce')\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFilas cargadas:       27,528\nColumnas disponibles: 142\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nArea: {1: 20200, 2: 7328}\nNivel educativo: {6.0: 5231, 5.0: 5175, 4.0: 5098, 9.0: 4541, 7.0: 3737, 8.0: 808, 10.0: 788, 1.0: 778, 2.0: 18}\n```\n:::\n:::\n\n\n> **Justificación:** `pd.read_spss()` preserva automáticamente las etiquetas de valor (*value labels*) del archivo, lo que permite verificar la codificación original antes de cualquier transformación. En esta versión de la ENEMDU, variables como `condact` vienen como texto etiquetado y deben recodificarse antes de usarse analíticamente.\n\n---\n\n## Exploración Inicial del Dataset\n\nEsta sección se ejecuta **sobre los datos crudos**, antes de cualquier modificación.\n\n### Vista previa de `condact`\n\n::: {#476e6602 .cell execution_count=3}\n``` {.python .cell-code}\n# condact llega como categoría de texto desde el .sav\ndf['condact'].head()\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n0    Población Económicamente Inactiva\n1    Población Económicamente Inactiva\n2                Empleo Adecuado/Pleno\n3                 Otro empleo no pleno\n4                 Otro empleo no pleno\nName: condact, dtype: str\n```\n:::\n:::\n\n\n### Distribución de frecuencias por columna\n\n::: {#62027c82 .cell execution_count=4}\n``` {.python .cell-code}\n# Revisión sistemática: detecta tipos, NaN estructurales e inconsistencias\nfor col in df.columns:\n    print(f\"Columna: {col}\")\n    print(df[col].value_counts(dropna=False))\n    print(\"-\" * 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nColumna: area\narea\n1    20200\n2     7328\nName: count, dtype: int64\n--------------------------------------------------\nColumna: ciudad\nciudad\n90150.0     3026\n170150.0    2633\n70150.0     2205\n10150.0     1908\n180150.0    1609\n            ... \n111152.0       9\n150450.0       9\n131750.0       8\n60850.0        7\n190251.0       7\nName: count, Length: 353, dtype: int64\n--------------------------------------------------\nColumna: conglomerado\nconglomerado\n900101    362\n000102    271\n900601    267\n000101    262\n000103    255\n         ... \n002406      8\n165501      8\n542803      7\n011804      7\n000153      7\nName: count, Length: 902, dtype: int64\n--------------------------------------------------\nColumna: panelm\npanelm\nPanel D41    7033\nPanel B31    6913\nPanel A31    6882\nPanel C42    6700\nName: count, dtype: int64\n--------------------------------------------------\nColumna: vivienda\nvivienda\nVivienda Dos                  3627\nVivienda Seis                 3605\nVivienda Uno                  3581\nVivienda Tres                 3569\nVivienda Cuatro               3567\nVivienda Siete                3487\nVivienda Cinco                3428\nVivienda Ocho (reemplazo)     1274\nVivienda Nueve (reemplazo)     870\nVivienda Diez (reemplazo)      520\nName: count, dtype: int64\n--------------------------------------------------\nColumna: hogar\nhogar\nHogar Uno     27464\nHogar Dos        61\nHogar Tres        3\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p01\np01\nPersona 1     8791\nPersona 2     7210\nPersona 3     5196\nPersona 4     3347\nPersona 5     1702\nPersona 6      717\nPersona 7      317\nPersona 8      123\nPersona 9       60\nPersona 10      28\nPersona 11      16\nPersona 12       8\nPersona 13       4\nPersona 14       4\nPersona 15       3\nPersona 16       2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p02\np02\n2    14225\n1    13303\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p03\np03\n15.0        511\n16.0        496\n18.0        491\n22.0        489\n17.0        486\n           ... \n98 y más     21\n95.0         19\n94.0         17\n97.0         12\n96.0          6\nName: count, Length: 99, dtype: int64\n--------------------------------------------------\nColumna: p04\np04\nHijo o Hija                 9963\nJefe                        8791\nCónyuge                     4754\nNieto o nieta               1692\nOtros parientes             1226\nPadres o suegros             368\nYerno o nuera                365\nOtros no parientes           359\nEmpleado(a) doméstico(a)      10\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p05a\np05a\nNinguno                               17198\nIESS, seguro general                   7466\nIESS, seguro  campesino                1286\nIESS, seguro general voluntario        1056\nISSFA, ISSPOL                           418\nSeguro privado con hospitalización       89\nSeguro privado sin hospitalización       15\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p05b\np05b\n6.0    27278\nNaN      250\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p06\np06\nSoltero(a)       9558\nCasado(a)        6812\nNaN              4021\nUnión libre      3696\nSeparado(a)      1250\nViudo(a)         1238\nDivorciado(a)     953\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p07\np07\nNo     18852\nSi      7322\nNaN     1354\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p08\np08\nNaN                 20206\nLa mañana            5300\nLa tarde             1032\nA distancia           543\nDos Jornadas          277\nLa Noche              168\nJornada Integral        2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p081\np081\nNaN               20206\nFiscal/Público     5261\nParticular         1654\nFiscomisional       365\nMunicipal            42\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p085\np085\nNaN                                                20206\nNo necesita equipo electrónico                      5971\nCuenta con equipo electrónico de uso exclusivo       936\nCuenta con equipo electrónico de uso compartido      212\nNo cuenta con equipo electrónico                     203\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p09\np09\nNaN                                   8676\nNo está interesado en estudiar        4335\nPor trabajo                           3963\nTerminó sus estudios                  3473\nEdad                                  3375\nFalta de recursos económicos          2094\nPor ayudar en quehaceres del hogar     678\nPor enfermedad o discapacidad          302\nPor cuidado de los hijos               271\nOtra                                   211\nPor falta de cupo                      103\nPor embarazo                            21\nPor fracaso escolar                     15\nPor asistir a nivelación SENESCYT        5\nLa familia no le permite estudiar        3\nNo hay establecimientos educación        3\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p10a\np10a\n6.0     5231\n5.0     5175\n4.0     5098\n9.0     4541\n7.0     3737\nNaN     1354\n8.0      808\n10.0     788\n1.0      778\n2.0       18\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p10b\np10b\n6.0     8035\n3.0     5160\n5.0     2711\n2.0     2687\nNaN     2132\n1.0     2049\n4.0     2044\n7.0      666\n10.0     639\n8.0      561\n9.0      531\n0.0      313\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p11\np11\nNaN    16459\nSi      9218\nNo      1851\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p12a\np12a\nNaN    21391\nSi      4187\nNo      1950\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p12b\np12b\nNaN           23341\n30410302.0      318\n30410102.0      206\n30330101.0      173\n30110301.0      137\n              ...  \n20710505.0        1\n20110101.0        1\n50830101.0        1\n50720403.0        1\n10830101.0        1\nName: count, Length: 519, dtype: int64\n--------------------------------------------------\nColumna: p15\np15\nMestizo            22554\nIndígena            1895\nNaN                 1354\nMontuvio             448\nNegro                436\nAfroecuatoriano      384\nMulato               275\nBlanco               173\nOtra                   9\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p15aa\np15aa\nEn esta ciudado  o parroquia rural    17568\nEn otro lugar del pais                 9332\nEn otro pais                            628\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p15ab\np15ab\nNaN         17568\n90150.0       615\n170150.0      507\n862.0         268\n180150.0      263\n            ...  \n120553.0        1\n130156.0        1\n131951.0        1\n240351.0        1\n240153.0        1\nName: count, Length: 685, dtype: int64\n--------------------------------------------------\nColumna: cod_inf\ncod_inf\nPersona 1     15132\nPersona 2      8240\nPersona 3      1771\nNaN            1354\nPersona 4       679\nPersona 5       211\nPersona 6        86\nPersona 7        40\nPersona 9         9\nPersona 8         5\nPersona 11        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p20\np20\nNo     13718\nSi     12456\nNaN     1354\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p21\np21\nNaN                                    13810\nNo realizó ninguna actividad           13255\nLabores agrícolas, cuidado animales      364\nAyudar en algún negocio familiar          60\nAtender negocio propio                    16\nHacer algo en casa por un ingreso          8\nBrindar algún servicio                     7\nOtra actividad por un ingreso              7\nFabricar algún producto                    1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p22\np22\nNaN    14273\nNo     12877\nSi       378\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p23\np23\nNaN                                27150\nVacaciones                           192\nEnfermedad accidente                  76\nSuspensión temporal del trabajo       69\nOtro                                  32\nLicencia con sueldo                    9\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p232\np232\nNaN    27150\nNo       253\nSi       125\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p233\np233\nNaN                27150\n3 meses o menos      369\nMás de 3 meses         9\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p24\np24\nNaN      14231\n40.0      4259\n24.0      1277\n20.0      1107\n30.0       740\n         ...  \n53.0         1\n61.0         1\n78.0         1\n120.0        1\n88.0         1\nName: count, Length: 81, dtype: int64\n--------------------------------------------------\nColumna: p25\np25\nNaN                                          20940\nSu trabajo así lo exige                       2374\nPor huelga o paro                             1655\nNo consiguió más trabajo                       747\nNo desea o no necesita trabajar más horas      621\nNo consiguió trabajo en otra parte             519\nMotivos de salud, familiares                   386\nPor estudios                                   263\nReducción actividades económicas                23\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p26\np26\nNaN                         20819\nHorario normal               6564\nOtro                           69\nHoras extras                   37\nHoras trabajo necesarias       31\nExceso trabajo                  8\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p27\np27\nNaN                                          14852\nNo desea trabajar más horas                  10127\nTrabajar más horas en otro trabajo             999\nTrabajar más horas en su trabajo actual        954\nCambiar el trabajo por otro con más horas      596\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p28\np28\nNaN    24979\nSi      2512\nNo        37\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p29\np29\nNaN     25016\n20.0      855\n10.0      508\n15.0      222\n30.0      149\n16.0      136\n24.0      103\n40.0      102\n8.0        88\n25.0       71\n12.0       57\n5.0        48\n32.0       24\n14.0       24\n18.0       18\n6.0        17\n22.0       14\n28.0       14\n4.0        11\n35.0        7\n26.0        7\n21.0        5\n9.0         5\n34.0        4\n7.0         4\n36.0        4\n19.0        4\n1.0         2\n13.0        2\n48.0        2\n2.0         1\n38.0        1\n31.0        1\n42.0        1\n29.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p29a\np29a\nNaN                                                               16743\nConsidera que ya trabaja demasiadas horas                          5451\nPiensa que no conseguirá un mejor trabajo                          3200\nSus condiciones de salud no le permiten trabajar más horas          812\nTiene que estudiar y no tiene más tiempo para trabajar              495\nTiene a cargo el cuidado de algún miembro de su hogar               468\nOtra                                                                213\nCree que con las horas que trabaja tiene un ingreso suficiente      146\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p30\np30\nNaN                                                 25016\nBuscar más trabajo                                   1142\nNo ha realizado ninguna gestión                       696\nPedir ayuda a amigos o familiares                     551\nPresentar solicitud a otros empleadores                62\nRegistro en agencia de empleo                          50\nConseguir recursos financieros adicionales             10\nBuscar terreno, edificio,... para propia empresa        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p31\np31\nNaN                                    25712\nLos ingresos no son suficientes         1578\nPor que no trabaja jornada completa      116\nDesea ejercer su profesión                89\nPor otras causas                          26\nInseguridad en su trabajo                  7\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p32\np32\nNaN                                               14651\nNo realizó ninguna gestión                        12329\nHablar con amigos o parientes                       181\nBuscar por Internet                                 161\nEnviar hoja de vida                                 150\nAcudir a sitios de contratación temporal             39\nAsistir a entrevistas                                10\nAcudir a agencias de empleo                           3\nBuscar en la prensa o radio                           2\nTratar de establecer su propio taller, negocio        2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p33\np33\nNaN     26980\n52.0       78\n8.0        76\n4.0        76\n2.0        50\n1.0        44\n12.0       37\n24.0       31\n3.0        27\n6.0        20\n20.0       16\n16.0       15\n48.0       14\n40.0       13\n10.0        8\n5.0         8\n32.0        7\n28.0        7\n36.0        5\n30.0        4\n7.0         3\n15.0        2\n14.0        2\n9.0         1\n11.0        1\n23.0        1\n96.0        1\n50.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p34\np34\nNaN                                          15199\nNo tiene tiempo                               5293\nNo está en edad de trabajar                   4347\nNo tiene necesidad de trabajar                1318\nEstá enfermo o incapacitado                   1214\nSu cónyuge o familia no le permiten             92\nNo cree poder encontrar                         34\nPiensa que no le darán trabajo                  10\nTrabajo ocasional                                9\nTiene trabajo para empezar inmediatamente        7\nEspera respuesta de un empleador                 3\nEspera cosecha o temporada de trabajo            2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p35\np35\nNaN    27463\nSi        51\nNo        14\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p36\np36\nNaN                 15250\nEstudiante           6486\nAma de casa          3088\nJubilado pensión     1471\nIncapacitado          796\nRentista              244\nOtro                  193\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p37\np37\nNaN    26929\nSi       414\nNo       185\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p38\np38\nNaN                       27114\nTerminación contrato        170\nRenuncia voluntaria          68\nDespido intempestivo         68\nOtro                         48\nFue mal en el negocio        32\nLiquidación empresa          14\nTerminó ciclo agrícola       14\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p39\np39\nNaN      27114\n52.0        70\n8.0         58\n4.0         51\n2.0         41\n12.0        29\n3.0         27\n24.0        19\n6.0         17\n20.0        15\n16.0        13\n1.0         10\n48.0        10\n10.0         8\n5.0          8\n40.0         6\n32.0         6\n28.0         5\n7.0          4\n14.0         3\n9.0          2\n15.0         2\n18.0         1\n11.0         1\n208.0        1\n104.0        1\n26.0         1\n30.0         1\n44.0         1\n144.0        1\n96.0         1\n36.0         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p40\np40\nNaN       13817\n150.0      1231\n5610.0      831\n4100.0      616\n8521.0      429\n          ...  \n2824.0        1\n5520.0        1\n121.0         1\n230.0         1\n893.0         1\nName: count, Length: 306, dtype: int64\n--------------------------------------------------\nColumna: p41\np41\nNaN       13817\n5223.0      613\n6112.0      554\n9213.0      466\n5221.0      447\n          ...  \n7125.0        1\n3143.0        1\n5111.0        1\n3154.0        1\n7312.0        1\nName: count, Length: 362, dtype: int64\n--------------------------------------------------\nColumna: p42\np42\nNaN                                               13817\nCuenta Propia                                      4837\nEmpleado privado                                   4251\nTrabajador del hogar no remunerado                 1306\nJornalero o peón                                   1287\nEmpleado de gobierno                               1266\nEmpleado(a) Doméstico(a)                            372\nPatrono                                             356\nTrabajador no del hogar no remunerado                23\nAyudante no remunerado de asalariado/jornalero       13\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p421\np421\nNaN    22390\nNo      3845\nSi      1293\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p422\np422\nNaN                                      26235\nLa mayor parte para la venta               763\nTodo para el consumo del hogar             226\nTodo para la venta                         163\nLa mayor parte para consumo del hogar      141\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p42a\np42a\nNaN    22390\nNo      5128\nSi        10\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p43\np43\nNaN                                                           20710\nCon contrato permanente / indefinido / estable o de planta     2622\nCon contrato temporal, ocasional o eventual                    2106\nPor jornal                                                     1226\nCon nombramiento                                                848\nPor obra, a destajo                                              10\nPor horas                                                         6\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p432\np432\nNaN        22803\nSi          2731\nNo          1992\nNo sabe        2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44a\np44a\nNaN    20710\nNo      4827\nSi      1991\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44b\np44b\nNaN    20710\nNo      6666\nSi       152\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44c\np44c\nNaN    20710\nNo      6497\nSi       321\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44d\np44d\nNaN    20710\nSi      3541\nNo      3277\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44e\np44e\nNaN    20710\nNo      5221\nSi      1597\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44f\np44f\nNaN    20710\nSi      3566\nNo      3252\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44g\np44g\nNaN    20710\nNo      6782\nSi        36\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44h\np44h\nNaN    20710\nNo      6817\nSi         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44i\np44i\nNaN    20710\nNo      6195\nSi       623\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44j\np44j\nNaN    20710\nSi      3507\nNo      3311\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p44k\np44k\nNaN    20710\nSi      3507\nNo      3311\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p45\np45\nNaN     14231\n2.0      1025\n1.0       986\n0.0       975\n10.0      965\n        ...  \n68.0        1\n69.0        1\n59.0        1\n85.0        1\n74.0        1\nName: count, Length: 79, dtype: int64\n--------------------------------------------------\nColumna: p46\np46\nNaN                               14231\nLocal patrono                      4784\nFinca o terreno                    1935\nLocal propio o arrendado           1406\nSu vivienda                        1228\nVivienda distinta a la suya        1135\nFinca terreno ajeno                 998\nSe desplaza                         991\nObra en construcción                566\nEn la calle                         224\nKiosco calle                         29\nLocal cooperativa u asociación        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p47a\np47a\nNaN             14231\nMenos de 100    10912\n100 y más        2385\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p47b\np47b\nNaN     16616\n1.0      4175\n2.0      2166\n3.0      1468\n4.0       758\n5.0       558\n10.0      234\n6.0       234\n20.0      202\n30.0      149\n50.0      130\n8.0       119\n15.0      119\n7.0        92\n12.0       70\n25.0       70\n40.0       69\n60.0       54\n80.0       30\n9.0        26\n70.0       22\n18.0       22\n35.0       14\n24.0       12\n45.0       10\n22.0        8\n16.0        8\n90.0        8\n23.0        7\n11.0        7\n14.0        7\n17.0        6\n28.0        6\n13.0        5\n75.0        4\n26.0        4\n38.0        4\n36.0        3\n55.0        3\n19.0        3\n27.0        3\n21.0        3\n34.0        2\n33.0        2\n52.0        2\n85.0        1\n65.0        1\n61.0        1\n68.0        1\n51.0        1\n53.0        1\n73.0        1\n92.0        1\n64.0        1\n67.0        1\n32.0        1\n31.0        1\n63.0        1\n47.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p48\np48\nNaN                      16964\nNo lleva contabilidad     7028\nCuaderno de cuentas       1824\nRegistros contables       1324\nNo sabe                    388\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p49\np49\nNaN        16964\nNo          5926\nSi          4356\nNo sabe      282\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p50\np50\nNaN           14231\nUno           12577\nMás de uno      720\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p51a\np51a\nNaN      14231\n40.0      5747\n20.0      1089\n30.0       805\n48.0       614\n         ...  \n19.0         1\n120.0        1\n59.0         1\n79.0         1\n98.0         1\nName: count, Length: 75, dtype: int64\n--------------------------------------------------\nColumna: p51b\np51b\nNaN     26808\n10.0      151\n20.0       89\n8.0        72\n5.0        60\n15.0       56\n6.0        41\n16.0       40\n14.0       36\n12.0       33\n4.0        32\n7.0        26\n24.0       15\n2.0        11\n3.0        11\n21.0        8\n9.0         7\n18.0        6\n28.0        5\n30.0        4\n13.0        4\n1.0         4\n11.0        3\n25.0        2\n22.0        2\n19.0        1\n40.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p51c\np51c\nNaN     26808\n0.0       700\n5.0         6\n3.0         3\n4.0         2\n10.0        2\n14.0        1\n6.0         1\n8.0         1\n1.0         1\n12.0        1\n20.0        1\n2.0         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p52\np52\nNaN       26808\n150.0       125\n111.0        36\n146.0        30\n141.0        30\n          ...  \n4530.0        1\n5221.0        1\n1520.0        1\n128.0         1\n3530.0        1\nName: count, Length: 120, dtype: int64\n--------------------------------------------------\nColumna: p53\np53\nNaN       26808\n9213.0       48\n9211.0       44\n6130.0       32\n5223.0       30\n          ...  \n3313.0        1\n1324.0        1\n3341.0        1\n3322.0        1\n1342.0        1\nName: count, Length: 126, dtype: int64\n--------------------------------------------------\nColumna: p54\np54\nNaN                                               26808\nCuenta Propia                                       426\nTrabajador del hogar no remunerado                  158\nJornalero o peón                                     54\nEmpleado privado                                     39\nPatrono                                              23\nEmpleado(a) Doméstico(a)                             10\nTrabajador no del hogar no remunerado                 5\nEmpleado de gobierno                                  3\nAyudante no remunerado de asalariado/jornalero        2\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p54a\np54a\nNaN    27079\nNo       448\nSi         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p55\np55\nNaN                            26808\nFinca o terreno                  248\nSu vivienda                      145\nLocal propio o arrendado          92\nVivienda distinta a la suya       85\nFinca terreno ajeno               56\nSe desplaza                       41\nLocal patrono                     34\nEn la calle                       12\nObra en construcción               6\nKiosco calle                       1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p56a\np56a\nNaN             26808\nMenos de 100      713\n100 y más           7\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p56b\np56b\nNaN     26815\n1.0       341\n2.0       191\n3.0        95\n4.0        47\n5.0        18\n6.0         8\n10.0        2\n8.0         2\n18.0        2\n60.0        1\n7.0         1\n40.0        1\n13.0        1\n15.0        1\n9.0         1\n19.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p57\np57\nNaN                      26825\nNo lleva contabilidad      585\nCuaderno de cuentas         93\nRegistros contables         17\nNo sabe                      8\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p58\np58\nNaN        26825\nNo           538\nSi           153\nNo sabe       12\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p61b1\np61b1\nNo aporta                    17061\nNaN                           5404\nIESS General                  3674\nIESS Voluntario                777\nSeguro Campesino               505\nSeguro del ISSFA o ISSPOL      102\nNo sabe                          5\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p63\np63\nNaN       22390\n0.0         501\n300.0       300\n600.0       296\n500.0       291\n          ...  \n1904.0        1\n826.0         1\n625.0         1\n9680.0        1\n1920.0        1\nName: count, Length: 310, dtype: int64\n--------------------------------------------------\nColumna: p64a\np64a\nNaN    22390\nNo      3088\nSi      2050\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p64b\np64b\nNaN      25478\n20.0       254\n30.0       187\n50.0       175\n10.0       161\n         ...  \n116.0        1\n162.0        1\n248.0        1\n600.0        1\n188.0        1\nName: count, Length: 139, dtype: int64\n--------------------------------------------------\nColumna: p65\np65\nNaN       22390\n0.0         947\n100.0       364\n200.0       334\n300.0       256\n          ...  \n168.0         1\n94.0          1\n265.0         1\n9000.0        1\n1440.0        1\nName: count, Length: 292, dtype: int64\n--------------------------------------------------\nColumna: p66\np66\nNaN      20710\n470.0      383\n400.0      323\n300.0      304\n200.0      283\n         ...  \n551.0        1\n791.0        1\n547.0        1\n411.0        1\n697.0        1\nName: count, Length: 677, dtype: int64\n--------------------------------------------------\nColumna: p67\np67\nNaN      20710\n0.0       3274\n45.0       371\n50.0       244\n44.0       227\n         ...  \n165.0        1\n186.0        1\n99.0         1\n147.0        1\n317.0        1\nName: count, Length: 254, dtype: int64\n--------------------------------------------------\nColumna: p68a\np68a\nNaN    20710\nNo      3615\nSi      3203\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p68b\np68b\nNaN      24325\n60.0       369\n50.0       209\n10.0       175\n8.0        151\n         ...  \n178.0        1\n202.0        1\n49.0         1\n117.0        1\n128.0        1\nName: count, Length: 201, dtype: int64\n--------------------------------------------------\nColumna: p69\np69\nNaN      26973\n0.0        101\n200.0       45\n100.0       40\n120.0       30\n         ...  \n48.0         1\n75.0         1\n78.0         1\n12.0         1\n64.0         1\nName: count, Length: 72, dtype: int64\n--------------------------------------------------\nColumna: p70a\np70a\nNaN    26973\nNo       332\nSi       223\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p70b\np70b\nNaN      27305\n20.0        32\n30.0        23\n10.0        20\n50.0        17\n5.0         12\n40.0        11\n80.0         8\n15.0         8\n12.0         8\n25.0         7\n100.0        6\n60.0         5\n70.0         5\n24.0         4\n8.0          4\n35.0         3\n22.0         3\n200.0        2\n16.0         2\n36.0         2\n26.0         2\n6.0          2\n4.0          2\n32.0         2\n21.0         2\n48.0         2\n28.0         2\n3.0          2\n43.0         1\n14.0         1\n75.0         1\n185.0        1\n7.0          1\n11.0         1\n96.0         1\n67.0         1\n111.0        1\n165.0        1\n27.0         1\n120.0        1\n89.0         1\n74.0         1\n55.0         1\n175.0        1\n68.0         1\n65.0         1\n64.0         1\n71.0         1\n122.0        1\n172.0        1\n360.0        1\n110.0        1\n56.0         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p71a\np71a\nNo     25731\nNaN     1354\nSi       443\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p71b\np71b\nNaN       27085\n200.0        56\n400.0        43\n300.0        40\n500.0        34\n          ...  \n340.0         1\n310.0         1\n660.0         1\n620.0         1\n2300.0        1\nName: count, Length: 63, dtype: int64\n--------------------------------------------------\nColumna: p72a\np72a\nNo     23908\nSi      2266\nNaN     1354\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p72b\np72b\nNaN       25262\n120.0       295\n600.0       136\n1000.0      106\n500.0        98\n          ...  \n1211.0        1\n510.0         1\n570.0         1\n255.0         1\n1524.0        1\nName: count, Length: 254, dtype: int64\n--------------------------------------------------\nColumna: p73a\np73a\nNo     19686\nSi      6488\nNaN     1354\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p73b\np73b\nNaN      21040\n5.0        888\n4.0        813\n100.0      495\n3.0        410\n         ...  \n84.0         1\n440.0        1\n255.0        1\n18.0         1\n348.0        1\nName: count, Length: 145, dtype: int64\n--------------------------------------------------\nColumna: p74a\np74a\nNo     25993\nNaN     1354\nSi       181\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p74b\np74b\nNaN         27347\n100.0          34\n200.0          34\n300.0          26\n150.0          17\n500.0          12\n400.0          11\n50.0           10\n600.0           7\n250.0           4\n120.0           4\n60.0            3\n450.0           2\n1000.0          2\n80.0            2\n140.0           1\n350.0           1\n470.0           1\n4500.0          1\n40.0            1\n5.0             1\n685.0           1\n1500.0          1\n384.0           1\n70.0            1\n999999.0        1\n800.0           1\n700.0           1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p75\np75\nNo     24839\nNaN     1354\nSi      1335\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p76\np76\nNaN      26193\n55.0       793\n100.0      338\n50.0        80\n65.0        18\n80.0        15\n75.0        12\n60.0        11\n85.0         8\n95.0         7\n79.0         6\n70.0         6\n104.0        5\n155.0        4\n78.0         3\n120.0        3\n92.0         3\n74.0         3\n90.0         2\n73.0         2\n82.0         2\n101.0        2\n112.0        2\n115.0        1\n57.0         1\n110.0        1\n130.0        1\n58.0         1\n270.0        1\n105.0        1\n96.0         1\n140.0        1\n72.0         1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p77\np77\nNo     26095\nNaN     1354\nSi        79\nName: count, dtype: int64\n--------------------------------------------------\nColumna: p78\np78\nNaN      27449\n240.0       76\n480.0        2\n720.0        1\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd01\nsd01\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd021\nsd021\nNaN    26929\nNo       525\nSi        74\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd022\nsd022\nNaN    26929\nNo       326\nSi       273\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd023\nsd023\nNaN    26929\nSi       549\nNo        50\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd024\nsd024\nNaN    26929\nSi       557\nNo        42\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd025\nsd025\nNaN    26929\nNo       595\nSi         4\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd026\nsd026\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd027\nsd027\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd028\nsd028\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd029\nsd029\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd0210\nsd0210\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd0211\nsd0211\nNaN    26929\nNo       599\nName: count, dtype: int64\n--------------------------------------------------\nColumna: sd03\nsd03\nNaN                                                      26929\nAntes no tuvo necesidad de trabajar                        171\nTerminación de contrato                                    169\nOtro, (especificar)                                         78\nRenuncia voluntaria                                         68\nDespido/Renuncia obligatoria                                63\nQuiebre o cierre de negocio                                 25\nCierre/clausura de la empresa donde trabajaba               14\nTerminación de ciclo agrícola o temporada del trabajo       11\nName: count, dtype: int64\n--------------------------------------------------\nColumna: ced01a\nced01a\nSi             26833\nNo responde      422\nNo               273\nName: count, dtype: int64\n--------------------------------------------------\nColumna: estrato\nestrato\n2612    1452\n2512    1023\n2812     956\n2613     824\n2513     808\n        ... \n0512      66\n0721      66\n2321      64\n0622      60\n2022      58\nName: count, Length: 150, dtype: int64\n--------------------------------------------------\nColumna: fexp\nfexp\n1700.373032     46\n5480.911024     44\n780.563424      42\n5620.541604     42\n10521.734965    40\n                ..\n297.670852       7\n765.027148       7\n3560.149756      7\n72.348215        7\n50.417524        7\nName: count, Length: 1288, dtype: int64\n--------------------------------------------------\nColumna: nnivins\nnnivins\nEducación Básica                11298\nEducación Media/Bachillerato     7943\nSuperior                         6137\nNaN                              1354\nNinguno                           778\nCentro de Alfabetización           18\nName: count, dtype: int64\n--------------------------------------------------\nColumna: ingrl\ningrl\nNaN       15539\n400.0       393\n500.0       391\n300.0       365\n200.0       364\n          ...  \n591.0         1\n3900.0        1\n1665.0        1\n446.0         1\n617.0         1\nName: count, Length: 1593, dtype: int64\n--------------------------------------------------\nColumna: ingpc\ningpc\n200.0     249\nNaN       228\n100.0     225\n250.0     185\n150.0     181\n         ... \n5200.0      1\n1211.0      1\n1359.0      1\n1732.0      1\n1208.0      1\nName: count, Length: 3450, dtype: int64\n--------------------------------------------------\nColumna: condact\ncondact\nPoblación Económicamente Inactiva                   8351\nEmpleo Adecuado/Pleno                               5814\nMenores de 15 años                                  5404\nOtro empleo no pleno                                3949\nSubempleo por insuficiencia de tiempo de trabajo    2262\nEmpleo no remunerado                                1010\nDesempleo abierto                                    548\nSubempleo por insuficiencia de ingresos               97\nDesempleo oculto                                      50\nEmpleo no clasificado                                 43\nName: count, dtype: int64\n--------------------------------------------------\nColumna: empleo\nempleo\nNaN                     14353\nPoblación con empleo    13175\nName: count, dtype: int64\n--------------------------------------------------\nColumna: desempleo\ndesempleo\nNaN                        26930\nPoblación con desempleo      598\nName: count, dtype: int64\n--------------------------------------------------\nColumna: secemp\nsecemp\nNaN                           14353\nSector Formal                  6724\nSector Informal                5822\nEmpleo Doméstico                348\nNo Clasificados por Sector      281\nName: count, dtype: int64\n--------------------------------------------------\nColumna: grupo1\ngrupo1\nNaN                                                     14353\nTrabajad. de los servicios y comerciantes                2799\nTrabajadores no calificados, ocupaciones elementales     2734\nTrabajad. calificados agropecuarios y pesqueros          2216\nProfesionales científicos e intelectuales                1498\nOficiales operarios y artesanos                          1445\nOperadores de instalac. máquinas y montad.                925\nTécnicos y profesionales de nivel medio                   837\nEmpleados de oficina                                      446\nPersonal direct./admin. pública y empresas                234\nFuerzas Armadas                                            41\nName: count, dtype: int64\n--------------------------------------------------\nColumna: rama1\nrama1\nNaN                                                          14353\nA. Agricultura, ganadería caza y silvicultura y pesca         3095\nG. Comercio, reparación vehículos                             2388\nC. Industrias manufactureras                                  1344\nI. Actividades de alojamiento y servicios de comida            963\nH. Transporte y almacenamiento                                 795\nF. Construcción                                                791\nP. Enseñanza                                                   676\nO .Administración pública, defensa y seguridad social          527\nQ. Actividades, servicios sociales y de salud                  489\nN. Actividades y servicios administrativos y de apoyo          476\nS. Otras actividades de servicios                              359\nT  Actividades en hogares privados con servicio doméstico      349\nM. Actividades profesionales, científicas y técnicas           348\nK. Actividades financieras y de seguros                        127\nB. Explotación de minas y canteras                             115\nJ. Información y comunicación                                  102\nR. Artes, entretenimiento y recreación                          97\nE. Distribución de agua, alcantarillado                         55\nL. Actividades inmobiliarias                                    38\nD. Suministros de electricidad, gas, aire acondicionado         35\nU  Actividades de organizaciones extraterritoriales              6\nName: count, dtype: int64\n--------------------------------------------------\nColumna: upm\nupm\n080453901801    46\n100350901001    44\n150350900902    42\n240154000502    42\n050651900601    40\n                ..\n060850902301     7\n090150542803     7\n130150011804     7\n190251900204     7\n200350000153     7\nName: count, Length: 1288, dtype: int64\n--------------------------------------------------\nColumna: id_vivienda\nid_vivienda\n06025000010405201    16\n15035090090207703    16\n09015007780307702    15\n10025490040207403    14\n08045490010205203    12\n                     ..\n24025001250306202     1\n24025001250306205     1\n24035000360607703     1\n24035000360607705     1\n24035000450207710     1\nName: count, Length: 8771, dtype: int64\n--------------------------------------------------\nColumna: id_hogar\nid_hogar\n060250000104052011    16\n150350900902077031    16\n090150077803077021    15\n100254900402074031    14\n080454900102052031    12\n                      ..\n240250012503062021     1\n240250012503062051     1\n240350003606077031     1\n240350003606077051     1\n240350004502077101     1\nName: count, Length: 8791, dtype: int64\n--------------------------------------------------\nColumna: id_persona\nid_persona\n01015000130406201101    1\n01015000130406201102    1\n01015000130406201103    1\n01015000130406202101    1\n01015000130406203101    1\n                       ..\n24035000450207708101    1\n24035000450207708102    1\n24035000450207708103    1\n24035000450207708104    1\n24035000450207710101    1\nName: count, Length: 27528, dtype: int64\n--------------------------------------------------\nColumna: periodo\nperiodo\nene-26    27528\nName: count, dtype: int64\n--------------------------------------------------\n```\n:::\n:::\n\n\n> **Justificación:** La exploración previa permite detectar: (1) variables con texto que deben reconvertirse a numérico, (2) NaN estructurales por diseño condicional del cuestionario, y (3) columnas que el archivo ya trae precalculadas — como `empleo` y `desempleo` — evitando recalcularlas innecesariamente.\n\n---\n\n## Recodificación de `condact`\n\nLa variable `condact` llega como texto etiquetado desde el `.sav`. Se mapea a la escala numérica oficial del INEC antes de cualquier otra transformación, ya que varias variables dependen de ella.\n\n::: {#3584bf5f .cell execution_count=5}\n``` {.python .cell-code}\n# Mapeo de etiquetas de texto a códigos numéricos oficiales INEC\n# Fuente: https://anda.inec.gob.ec/anda/index.php/catalog/1048/datafile/F17/V1815\nmapa_condact = {\n    \"Empleo Adecuado/Pleno\": 1,\n    \"Subempleo por insuficiencia de tiempo de trabajo\": 2,\n    \"Subempleo por insuficiencia de ingresos\": 3,\n    \"Otro empleo no pleno\": 4,\n    \"Empleo no remunerado\": 5,\n    \"Empleo no clasificado\": 6,\n    \"Desempleo abierto\": 7,\n    \"Desempleo oculto\": 8,\n    \"Población Económicamente Inactiva\": 9\n}\n\ndf[\"condact\"] = df[\"condact\"].map(mapa_condact)\n\n# Menores de 15 años reciben código 0: quedan fuera de la PET\n# p03 viene como string tras el strip global -> convertir a numérico primero\ndf[\"p03\"] = pd.to_numeric(df[\"p03\"], errors='coerce')\ndf.loc[df['p03'] < 15, 'condact'] = 0\n\nprint(\"Distribución de condact tras recodificación:\")\nprint(df[\"condact\"].value_counts())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistribución de condact tras recodificación:\ncondact\n9.0    8351\n1.0    5814\n0.0    5404\n4.0    3949\n2.0    2262\n5.0    1010\n7.0     548\n3.0      97\n8.0      50\n6.0      43\nName: count, dtype: int64\n```\n:::\n:::\n\n\n> **Justificación:** La escala numérica 1–9 permite usar `.between()` para definir subpoblaciones de forma compacta. El código 0 para menores de 15 años los excluye explícitamente de la Población en Edad de Trabajar (PET), en línea con la metodología INEC. Este paso debe ocurrir antes del manejo de NaN porque los filtros de edad usan `p03`.\n\n---\n\n## Construcción de Horas Trabajadas Totales\n\nEl archivo fuente no incluye una variable de horas totales precalculada. Se construye sumando las horas del empleo principal (`p51a`) y del empleo secundario (`p51b`), que son las únicas columnas con valores numéricos de horas en el cuestionario.\n\n::: {#1295c2d5 .cell execution_count=6}\n``` {.python .cell-code}\n# Convertir a numérico (vienen como Categorical desde el .sav)\ndf['p51a'] = pd.to_numeric(df['p51a'], errors='coerce')  # horas empleo principal\ndf['p51b'] = pd.to_numeric(df['p51b'], errors='coerce')  # horas empleo secundario\n\n# Horas totales = suma de ambos empleos (NaN si no trabaja en ninguno)\ndf['horas_trabajo_totales'] = df['p51a'].add(df['p51b'], fill_value=0)\ndf.loc[df['p51a'].isna() & df['p51b'].isna(), 'horas_trabajo_totales'] = np.nan\n\n# Versión para visualización: 0 en lugar de NaN (inactivos y desempleados)\ndf['horas_visual'] = df['horas_trabajo_totales'].fillna(0)\n\nprint(\"Distribución de horas totales trabajadas:\")\nprint(df['horas_trabajo_totales'].describe())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDistribución de horas totales trabajadas:\ncount    13297.000000\nmean        35.888772\nstd         13.288100\nmin          1.000000\n25%         28.000000\n50%         40.000000\n75%         40.000000\nmax        120.000000\nName: horas_trabajo_totales, dtype: float64\n```\n:::\n:::\n\n\n> **Justificación:** `p51a` registra horas en el trabajo principal y `p51b` en el secundario. Se usa `fill_value=0` en la suma para que quien solo tiene un empleo no pierda sus horas por el NaN del otro. Sin embargo, si ambas columnas son NaN (persona sin empleo), el resultado se fuerza a NaN para no introducir ceros artificiales en los promedios de ocupados.\n\n---\n\n## Manejo de Valores Faltantes\n\nEsta sección opera **sobre columnas que ya existen** en el dataframe. Ejecutarla antes de la recodificación y construcción de variables causaría `KeyError`.\n\nLa ENEMDU tiene diseño de cuestionario condicional: preguntas sobre búsqueda de empleo solo se hacen a desempleados, preguntas laborales solo a ocupados, etc. Los NaN en esas variables son **ausencias estructurales por diseño**, no errores de medición.\n\n### Variables categóricas: NaN → `\"No hay dato\"`\n\n::: {#5be63930 .cell execution_count=7}\n``` {.python .cell-code}\n# Se usan los nombres originales del .sav porque el renombrado\n# ocurre más adelante al crear df_final.\n# p06 = estado_civil | p07 = asiste_a_clases\n# Estas columnas son Categorical, por lo que se convierte a str antes de rellenar.\ncols_cat = ['p06', 'p07']\nfor col in cols_cat:\n    df[col] = df[col].astype(str).replace('nan', 'No hay dato')\n```\n:::\n\n\n> **Justificación:** Las columnas Categorical de SPSS no admiten valores nuevos sin registrarlos primero como categoría válida. Convertir a `str` resuelve esto y produce una columna de texto directamente usable en gráficos. El valor `'nan'` que genera `.astype(str)` se reemplaza por la etiqueta `'No hay dato'` para claridad visual.\n\n---\n\n## Mapeo de Variables Geográficas y Sociodemográficas\n\n### Mapeo de ciudades\n\n::: {#1cd7d3a4 .cell execution_count=8}\n``` {.python .cell-code}\n# El catálogo traduce los códigos numéricos del .sav a nombres legibles\nciudades = pd.read_excel('SPSS/Ciudades.xlsx')\nciudades.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Value</th>\n      <th>Category</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>90150</td>\n      <td>Guayaquil</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>170150</td>\n      <td>Quito</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>130850</td>\n      <td>Manta</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>80150</td>\n      <td>Esmeraldas</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>110150</td>\n      <td>Loja</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#343f223b .cell execution_count=9}\n``` {.python .cell-code}\n# ciudad viene como float64 (ej. 10150.0) y el catálogo tiene int64 (10150).\n# Se convierte a Int64 nullable para alinear tipos sin perder los NaN.\ndf['ciudad'] = df['ciudad'].astype('Int64').map(ciudades.set_index('Value')['Category'])\ndf['ciudad'] = df['ciudad'].fillna('No hay dato')\n\nprint(f\"Ciudades distintas en la muestra: {df['ciudad'].nunique()}\")\ndf['ciudad'].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCiudades distintas en la muestra: 331\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nciudad\nGuayaquil                         3026\nQuito                             2633\nMachala                           2205\nCuenca                            1908\nAmbato                            1609\nEsmeraldas                         582\nSanto domingo de los colorados     434\nIbarra                             423\nLoja                               388\nNueva loja                         314\nName: count, dtype: int64\n```\n:::\n:::\n\n\n> **Justificación:** El archivo `.sav` almacena ciudades como `float64` (ej. `10150.0`) mientras que el catálogo `Ciudades.xlsx` usa `int64` (`10150`). La discrepancia de tipo impide el mapeo directo. Convertir a `Int64` nullable de pandas alinea los tipos sin perder los NaN, permitiendo que `.map()` encuentre todas las correspondencias correctamente.\n\n### Construcción de `adec` (empleo adecuado)\n\n::: {#082f3831 .cell execution_count=10}\n``` {.python .cell-code}\n# adec no viene precalculada en el archivo; se deriva de condact\n# condact == 1 corresponde a Empleo Adecuado/Pleno\ndf['adec'] = np.where(df['condact'] == 1, 1.0, np.nan)\n```\n:::\n\n\n> **Justificación:** A diferencia de `empleo` y `desempleo`, la variable `adec` no viene en el archivo fuente. Se construye desde `condact` ya recodificado: código 1 = Empleo Adecuado/Pleno. Se usa `np.nan` en lugar de `0` para ser consistente con la convención de indicadores del INEC.\n\n### Mapeo de etnia\n\n::: {#4e4e3f5c .cell execution_count=11}\n``` {.python .cell-code}\n# La etnia está en p15 (autoidentificación étnica)\nmapping_etnia = {\n    1: 'Mestizo',\n    2: 'Indígena',\n    3: 'Afro/Negro',\n    4: 'Mulato',\n    5: 'Blanco',\n    6: 'Otros'\n}\ndf['etnia_nombre'] = pd.to_numeric(df['p15'], errors='coerce') \\\n                       .map(mapping_etnia).fillna('No hay dato')\n```\n:::\n\n\n> **Justificación:** La variable de autoidentificación étnica se encuentra en `p15`, no en una columna llamada `etnia`. Se convierte a numérico primero porque viene como Categorical desde el `.sav`, y se rellena con `'No hay dato'` para no excluir registros.\n\n---\n\n## Selección Final de Variables\n\nSe selecciona el subconjunto relevante para el análisis visual y se renombran con etiquetas descriptivas en español. **Este paso ocurre al final**, después de que todas las columnas necesarias han sido creadas.\n\n::: {#67ff53dd .cell execution_count=12}\n``` {.python .cell-code}\ndf_final = df[[\n    'horas_trabajo_totales', 'horas_visual',\n    'area', 'ciudad', 'etnia_nombre',\n    'condact', 'empleo', 'desempleo', 'adec',\n    'p01', 'p02', 'p03', 'p05b', 'p06', 'p07',\n    'p10a', 'p32', 'p38', 'p42', 'p45',\n    'ingrl', 'ingpc'\n]].rename(columns={\n    'p01':          'personas_hogar',\n    'p02':          'genero',\n    'p03':          'edad',\n    'p05b':         'seguro',\n    'p06':          'estado_civil',\n    'p07':          'asiste_a_clases',\n    'condact':      'condicion_actividad',\n    'adec':         'empleo_adecuado',\n    'p10a':         'nivel_educativo',\n    'p45':          'tiempo_experiencia',\n    'p32':          'como_busca_empleo',\n    'p38':          'razon_dejo_trabajo',\n    'p42':          'ocupacion_actual',\n    'etnia_nombre': 'etnia',\n    'ingrl':        'ingreso_laboral',\n    'ingpc':        'ingreso_per_capita'\n})\n```\n:::\n\n\n> **Justificación:** Se incluyen `ingrl` e `ingpc` porque el archivo sí las trae precalculadas y son relevantes para el análisis laboral. Se excluyen variables operativas del cuestionario (identificadores de vivienda, hogar, conglomerado) que no aportan al análisis sustantivo.\n\n### Verificación del dataset final\n\n::: {#b23d77fd .cell execution_count=13}\n``` {.python .cell-code}\ndf_final.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 27528 entries, 0 to 27527\nData columns (total 22 columns):\n #   Column                 Non-Null Count  Dtype  \n---  ------                 --------------  -----  \n 0   horas_trabajo_totales  13297 non-null  float64\n 1   horas_visual           27528 non-null  float64\n 2   area                   27528 non-null  int64  \n 3   ciudad                 27528 non-null  str    \n 4   etnia                  27528 non-null  str    \n 5   condicion_actividad    27528 non-null  float64\n 6   empleo                 13175 non-null  str    \n 7   desempleo              598 non-null    str    \n 8   empleo_adecuado        5814 non-null   float64\n 9   personas_hogar         27528 non-null  str    \n 10  genero                 27528 non-null  int64  \n 11  edad                   27507 non-null  float64\n 12  seguro                 27278 non-null  float64\n 13  estado_civil           23507 non-null  str    \n 14  asiste_a_clases        26174 non-null  str    \n 15  nivel_educativo        26174 non-null  float64\n 16  como_busca_empleo      12877 non-null  str    \n 17  razon_dejo_trabajo     414 non-null    str    \n 18  ocupacion_actual       13711 non-null  str    \n 19  tiempo_experiencia     13297 non-null  str    \n 20  ingreso_laboral        11989 non-null  str    \n 21  ingreso_per_capita     27300 non-null  float64\ndtypes: float64(8), int64(2), str(12)\nmemory usage: 4.6 MB\n```\n:::\n:::\n\n\n::: {#d90b4ebb .cell execution_count=14}\n``` {.python .cell-code}\nprint(f\"Total filas:    {len(df_final):,}\")\nprint(f\"Total columnas: {len(df_final.columns)}\")\nprint(f\"Ciudades representadas: {df_final['ciudad'].nunique()}\")\ndf_final['ciudad'].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal filas:    27,528\nTotal columnas: 22\nCiudades representadas: 331\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nciudad\nGuayaquil                         3026\nQuito                             2633\nMachala                           2205\nCuenca                            1908\nAmbato                            1609\nEsmeraldas                         582\nSanto domingo de los colorados     434\nIbarra                             423\nLoja                               388\nNueva loja                         314\nName: count, dtype: int64\n```\n:::\n:::\n\n\n---\n\n## Exportación del Dataset Limpio\n\n::: {#a711cffc .cell execution_count=15}\n``` {.python .cell-code}\n# ── Forzar tipos numéricos antes de exportar ────────────────────\n# Las columnas Categorical del .sav pueden exportarse como object al CSV.\n# Se convierten explícitamente para que las visualizaciones las lean como números.\ncols_numericas = [\n    'edad', 'personas_hogar', 'nivel_educativo',\n    'condicion_actividad', 'empleo_adecuado', 'desempleado',\n    'horas_trabajo_totales', 'horas_visual',\n    'ingreso_laboral', 'ingreso_per_capita'\n]\nfor col in cols_numericas:\n    if col in df_final.columns:\n        df_final[col] = pd.to_numeric(df_final[col], errors='coerce')\n\n# area viene como Categorical texto ('Urbana'/'Rural') -> convertir a código numérico\nif 'area' in df_final.columns:\n    df_final['area'] = df_final['area'].astype(str).map(\n        {'Urbana': 1, 'Rural': 2, '1.0': 1, '2.0': 2, '1': 1, '2': 2}\n    )\n\n# genero y seguro pueden venir como Categorical -> numérico\nfor col in ['genero', 'seguro']:\n    if col in df_final.columns:\n        df_final[col] = pd.to_numeric(df_final[col], errors='coerce')\n\n# empleo y desempleado vienen como texto etiquetado desde el .sav\n# los convertimos a 1.0/NaN para que sean usables como indicadores\nif 'empleo' in df_final.columns:\n    df_final['empleo'] = df_final['empleo'].map(\n        lambda x: 1.0 if str(x).strip() in ['Población con empleo', '1.0', '1'] else float('nan')\n    )\nif 'desempleado' in df_final.columns:\n    df_final['desempleado'] = df_final['desempleado'].map(\n        lambda x: 1.0 if str(x).strip() in ['Población con desempleo', '1.0', '1'] else float('nan')\n    )\n\ndf_final.to_csv('SPSS/ENEMDU_clean.csv', index=False)\nprint('Dataset exportado exitosamente → SPSS/ENEMDU_clean.csv')\nprint(df_final[['area','genero','nivel_educativo','ingreso_laboral','empleo_adecuado']].dtypes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataset exportado exitosamente → SPSS/ENEMDU_clean.csv\narea                 int64\ngenero               int64\nnivel_educativo    float64\ningreso_laboral    float64\nempleo_adecuado    float64\ndtype: object\n```\n:::\n:::\n\n\n> **Justificación:** Se exporta en CSV para garantizar compatibilidad con las herramientas de visualización (Altair, Plotly, etc.) y facilitar el control de versiones. El archivo fuente `.sav` original no se modifica en ningún momento.\n\n---\n\n## Resumen de Decisiones de Limpieza\n\n| Decisión | Columnas afectadas | Razón |\n|---|---|---|\n| Explorar antes de transformar | Todas | Diagnosticar tipos, NaN y columnas precalculadas |\n| Recodificar `condact` primero | `condact` | Base de todas las variables derivadas; debe ser numérico |\n| Código 0 para menores de 15 | `condact`, `p03` | Metodología INEC: PET inicia a los 15 años |\n| No reconstruir variables precalculadas | `empleo`, `desempleo`, `adec` | El `.sav` ya las trae; recalcularlas introduciría inconsistencias |\n| Horas = `p51a + p51b` | `horas_trabajo_totales` | Única fuente numérica de horas en el cuestionario |\n| NaN bilateral → NaN en horas | `horas_trabajo_totales` | Evita introducir ceros para inactivos en promedios de ocupados |\n| `.astype(str)` antes de rellenar | `p06`, `p07`, `ciudad` | Columnas Categorical no admiten categorías nuevas directamente |\n| `'No hay dato'` en categóricas | `ciudad`, `estado_civil`, `asiste_a_clases`, `etnia` | Evita excluir registros en visualizaciones agregadas |\n| Renombrado al final en `df_final` | Todas las seleccionadas | Evita `KeyError` al usar nombres descriptivos antes de que existan |\n| Exportación CSV | — | Compatibilidad universal con herramientas de visualización |\n\n",
    "supporting": [
      "data_cleaning1_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}